In [1]:
using DIVAnd
using PyPlot
using NCDatasets
using Missings
using Interpolations

if VERSION >= v"0.7"
    using Random
    using DelimitedFiles
    using Statistics
    using Printf
    using FileIO
else
    using Compat: @info, @warn, range, cat
end

In [27]:
# Module where the output grid and the modules are defined
include("../src/emodnet_bio_grid.jl");
include("../src/make_traits_products.jl");

In [4]:
datafile = "/home/ctroupin/tmp/Emodnet-Bio/Traits/Benthos_Traits_ab.csv"
outputfile = joinpath(outputdirTraits, replace(basename(datafile), ".csv" => ".nc"))

"../output/traits/Benthos_Traits_ab.nc"

## Read data

In [5]:
if isfile(datafile)
    data, header = readdlm(datafile,',',header = true);
else
    @warn "Data file doesn't exist"
end
varlist = header[5:end];
ntraits = length(varlist);
@info "Working on $(ntraits) traits"

┌ Info: Working on 62 traits
└ @ Main In[5]:8


In [29]:
?readdlm

search: readdlm readdir



```
readdlm(source, T::Type; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt", Int64)
4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8

julia> readdlm("delim_file.txt", Float64)
4×2 Array{Float64,2}:
 1.0  5.0
 2.0  6.0
 3.0  7.0
 4.0  8.0

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, T::Type; options...)
```

The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',', Float64)
4×2 Array{Float64,2}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> rm("delim_file.txt")
```

---

```
readdlm(source; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt")
4×2 Array{Any,2}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar; options...)
```

The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Array{Float64,2}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> rm("delim_file.txt")

julia> z = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x z], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Array{Any,2}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, eol::AbstractChar; options...)
```

If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

---

```
readdlm(source, delim::AbstractChar, T::Type, eol::AbstractChar; header=false, skipstart=0, skipblanks=true, use_mmap, quotes=true, dims, comments=false, comment_char='#')
```

Read a matrix from the source where each line (separated by `eol`) gives one row, with elements separated by the given delimiter. The source can be a text file, stream or byte array. Memory mapped files can be used by passing the byte array representation of the mapped segment as source.

If `T` is a numeric type, the result is an array of that type, with any non-numeric elements as `NaN` for floating-point types, or zero. Other useful values of `T` include `String`, `AbstractString`, and `Any`.

If `header` is `true`, the first row of data will be read as header and the tuple `(data_cells, header_cells)` is returned instead of only `data_cells`.

Specifying `skipstart` will ignore the corresponding number of initial lines from the input.

If `skipblanks` is `true`, blank lines in the input will be ignored.

If `use_mmap` is `true`, the file specified by `source` is memory mapped for potential speedups. Default is `true` except on Windows. On Windows, you may want to specify `true` if the file is large, and is only read once and not written to.

If `quotes` is `true`, columns enclosed within double-quote (") characters are allowed to contain new lines and column delimiters. Double-quote characters within a quoted field must be escaped with another double-quote.  Specifying `dims` as a tuple of the expected rows and columns (including header, if any) may speed up reading of large files.  If `comments` is `true`, lines beginning with `comment_char` and text following `comment_char` in any line are ignored.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end

julia> readdlm("delim_file.txt", '\t', Int, '\n')
4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8
```


### Get coordinates

In [6]:
indexlon = findfirst(header .== "x").I[2];
indexlat = findfirst(header .== "y").I[2];
obslon = Vector{Float64}(data[:,indexlon]);
obslat = Vector{Float64}(data[:,indexlat]);

### Mask and bathymetry

In [7]:
# Grid stored in emodnet_bio_grid.jl
xi,yi = DIVAnd.ndgrid(gridlonBenthos, gridlatBenthos);

# Mask
topodir = "../data/"
topofile = joinpath(topodir, "gebco_30sec_8.nc");

if isfile(topofile)
    bx, by, b = DIVAnd.load_bath(topofile,true,gridlonBenthos, gridlatBenthos);
    xmask, ymask, mmask = DIVAnd.load_mask(topofile,true,gridlonBenthos, gridlatBenthos,[0]);
else
    @error "Bathymetry file doesn't exist"
end
mmask = mmask[:,:,1]
@info size(mmask)

# Metrics
pm = ones(size(xi)) / (xi[2,1]-xi[1,1]);
pn = ones(size(xi)) / (yi[1,2]-yi[1,1]);

┌ Info: (451, 371)
└ @ Main In[7]:15


## Parameter choice 

In [10]:
# Correlation length
len = 4.;
# Observational error variance normalized by the background error variance
epsilon2 = 10.;

The weight is decreased for very close points.

In [11]:
rdiag=1.0./DIVAnd.weight_RtimesOne((obslon, obslat),(0.03,0.03))
@show maximum(rdiag),mean(rdiag);
epsilon2 = epsilon2*rdiag;

(maximum(rdiag), mean(rdiag)) = (439.41430029504994, 33.49833660679846)


## Analysis
All the fields are stored in a 3D array, to be later written to a netCDF file.

In [12]:
# Allocate matrix with all the gridded fields
trait_all = Array{Float64}(undef, ntraits, length(gridlonBenthos), length(gridlatBenthos));
trait_err = Array{Float64}(undef, length(gridlonBenthos), length(gridlatBenthos));
for i in 1:ntraits
    @info "Working on $(varlist[i])" 
    indextrait = findfirst(header .== varlist[i]).I[2];
    trait = Vector{Float64}(data[:,indextrait]) 
    traits_interp = traits_analysis(obslon, obslat, trait);
    if i == 1
        @info "Computing error field"
        trait_err = traits_error(obslon, obslat, trait);
    end
    trait_all[i,:,:] = traits_interp;
end

┌ Info: Working on Body.length..1cm
└ @ Main In[12]:5


 12.817391 seconds (27.17 M allocations: 2.641 GiB, 14.58% gc time)


┌ Info: Computing error field
└ @ Main In[12]:10
┌ Info: Working on Body.length.1.3cm
└ @ Main In[12]:5


  1.787046 seconds (2.30 M allocations: 1.450 GiB, 56.17% gc time)


┌ Info: Working on Body.length.3.10cm
└ @ Main In[12]:5


  1.799711 seconds (2.30 M allocations: 1.450 GiB, 55.68% gc time)


┌ Info: Working on Body.length.10.20cm
└ @ Main In[12]:5


  1.840429 seconds (2.30 M allocations: 1.450 GiB, 56.25% gc time)


┌ Info: Working on Body.length.20.50cm
└ @ Main In[12]:5


  1.815266 seconds (2.30 M allocations: 1.450 GiB, 56.43% gc time)


┌ Info: Working on Body.length..50cm
└ @ Main In[12]:5


  3.101076 seconds (2.30 M allocations: 1.450 GiB, 32.97% gc time)


┌ Info: Working on Fragility.Fragile
└ @ Main In[12]:5


  1.911733 seconds (2.30 M allocations: 1.450 GiB, 56.18% gc time)


┌ Info: Working on Fragility.Intermediate
└ @ Main In[12]:5


  1.918727 seconds (2.30 M allocations: 1.450 GiB, 56.25% gc time)


┌ Info: Working on Fragility.Robust
└ @ Main In[12]:5


  2.090163 seconds (2.30 M allocations: 1.450 GiB, 51.81% gc time)


┌ Info: Working on Motility.Swimmer
└ @ Main In[12]:5


  1.811582 seconds (2.30 M allocations: 1.450 GiB, 55.56% gc time)


┌ Info: Working on Motility.Tubicolous
└ @ Main In[12]:5


  1.835329 seconds (2.30 M allocations: 1.450 GiB, 55.95% gc time)


┌ Info: Working on Motility.Crawler
└ @ Main In[12]:5


  1.843830 seconds (2.30 M allocations: 1.450 GiB, 57.12% gc time)


┌ Info: Working on Motility.Crawler.Swimmer
└ @ Main In[12]:5


  1.899490 seconds (2.30 M allocations: 1.450 GiB, 54.12% gc time)


┌ Info: Working on Motility.Tubicolous.Crawler.Swimmer
└ @ Main In[12]:5


  1.948548 seconds (2.30 M allocations: 1.450 GiB, 56.75% gc time)


┌ Info: Working on Motility.Sessile
└ @ Main In[12]:5


  1.840321 seconds (2.30 M allocations: 1.450 GiB, 56.05% gc time)


┌ Info: Working on Motility.Sessile.Crawler.Swimmer
└ @ Main In[12]:5


  1.930383 seconds (2.30 M allocations: 1.450 GiB, 54.80% gc time)


┌ Info: Working on Lifespan..1year
└ @ Main In[12]:5


  1.858312 seconds (2.30 M allocations: 1.450 GiB, 57.18% gc time)


┌ Info: Working on Lifespan.1.3years
└ @ Main In[12]:5


  1.928369 seconds (2.30 M allocations: 1.450 GiB, 54.47% gc time)


┌ Info: Working on Lifespan.10.20years
└ @ Main In[12]:5


  1.869062 seconds (2.30 M allocations: 1.450 GiB, 57.18% gc time)


┌ Info: Working on Lifespan.3.10years
└ @ Main In[12]:5


  1.797966 seconds (2.30 M allocations: 1.450 GiB, 56.37% gc time)


┌ Info: Working on Lifespan..20years
└ @ Main In[12]:5


  1.784489 seconds (2.30 M allocations: 1.450 GiB, 56.54% gc time)


┌ Info: Working on Maturity..1year
└ @ Main In[12]:5


  1.789986 seconds (2.30 M allocations: 1.450 GiB, 56.78% gc time)


┌ Info: Working on Maturity.1.3years
└ @ Main In[12]:5


  1.772017 seconds (2.30 M allocations: 1.450 GiB, 56.23% gc time)


┌ Info: Working on Maturity.3.5years
└ @ Main In[12]:5


  1.786470 seconds (2.30 M allocations: 1.450 GiB, 55.94% gc time)


┌ Info: Working on Maturity..5years
└ @ Main In[12]:5


  1.788518 seconds (2.30 M allocations: 1.450 GiB, 55.85% gc time)


┌ Info: Working on Reproductive.frequency.Seasonal
└ @ Main In[12]:5


  2.203055 seconds (2.30 M allocations: 1.450 GiB, 47.10% gc time)


┌ Info: Working on Reproductive.frequency.Continuous
└ @ Main In[12]:5


  2.143929 seconds (2.30 M allocations: 1.450 GiB, 52.41% gc time)


┌ Info: Working on Fecundity..100
└ @ Main In[12]:5


  1.986764 seconds (2.30 M allocations: 1.450 GiB, 55.71% gc time)


┌ Info: Working on Fecundity.100.1000
└ @ Main In[12]:5


  1.834570 seconds (2.30 M allocations: 1.450 GiB, 55.54% gc time)


┌ Info: Working on Fecundity.1000.10000
└ @ Main In[12]:5


  1.946988 seconds (2.30 M allocations: 1.450 GiB, 55.92% gc time)


┌ Info: Working on Fecundity.10000.100000
└ @ Main In[12]:5


  2.049150 seconds (2.30 M allocations: 1.450 GiB, 56.44% gc time)


┌ Info: Working on Fecundity.100000.1000000
└ @ Main In[12]:5


  1.904431 seconds (2.30 M allocations: 1.450 GiB, 57.58% gc time)


┌ Info: Working on Fecundity..1000000
└ @ Main In[12]:5


  2.078926 seconds (2.30 M allocations: 1.450 GiB, 49.51% gc time)


┌ Info: Working on Offspring.type.Egg
└ @ Main In[12]:5


  1.920067 seconds (2.30 M allocations: 1.450 GiB, 56.48% gc time)


┌ Info: Working on Offspring.type.Larva
└ @ Main In[12]:5


  1.899555 seconds (2.30 M allocations: 1.450 GiB, 57.38% gc time)


┌ Info: Working on Offspring.type.Juvenile
└ @ Main In[12]:5


  1.880929 seconds (2.30 M allocations: 1.450 GiB, 53.50% gc time)


┌ Info: Working on Offspring.size..100
└ @ Main In[12]:5


  1.903660 seconds (2.30 M allocations: 1.450 GiB, 55.74% gc time)


┌ Info: Working on Offspring.size.100.500
└ @ Main In[12]:5


  2.183192 seconds (2.30 M allocations: 1.450 GiB, 52.65% gc time)


┌ Info: Working on Offspring.size.500.1500
└ @ Main In[12]:5


  2.495117 seconds (2.30 M allocations: 1.450 GiB, 59.83% gc time)


┌ Info: Working on Offspring.size..1500
└ @ Main In[12]:5


  4.036690 seconds (2.30 M allocations: 1.450 GiB, 44.07% gc time)


┌ Info: Working on Offspring.protection.None
└ @ Main In[12]:5


  3.714643 seconds (2.30 M allocations: 1.450 GiB, 45.76% gc time)


┌ Info: Working on Offspring.protection.Gel
└ @ Main In[12]:5


  5.034166 seconds (2.30 M allocations: 1.450 GiB, 46.21% gc time)


┌ Info: Working on Offspring.protection.Capsule
└ @ Main In[12]:5


  4.572441 seconds (2.30 M allocations: 1.450 GiB, 42.73% gc time)


┌ Info: Working on Offspring.protection.Burrying
└ @ Main In[12]:5


  4.419895 seconds (2.30 M allocations: 1.450 GiB, 34.81% gc time)


┌ Info: Working on Offspring.protection.Brooding
└ @ Main In[12]:5


  4.805497 seconds (2.30 M allocations: 1.450 GiB, 38.14% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.Null
└ @ Main In[12]:5


  4.221135 seconds (2.30 M allocations: 1.450 GiB, 39.32% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.1.15days
└ @ Main In[12]:5


  4.672113 seconds (2.30 M allocations: 1.450 GiB, 39.70% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.15.30days
└ @ Main In[12]:5


  5.295217 seconds (2.30 M allocations: 1.450 GiB, 38.82% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.1.2months
└ @ Main In[12]:5


  4.436168 seconds (2.30 M allocations: 1.450 GiB, 41.67% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.2.6months
└ @ Main In[12]:5


  4.845383 seconds (2.30 M allocations: 1.450 GiB, 36.41% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration..6months
└ @ Main In[12]:5


  3.412734 seconds (2.30 M allocations: 1.450 GiB, 50.62% gc time)


┌ Info: Working on Trophy.De
└ @ Main In[12]:5


  1.854385 seconds (2.30 M allocations: 1.450 GiB, 55.08% gc time)


┌ Info: Working on Trophy.SuDe
└ @ Main In[12]:5


  1.888130 seconds (2.30 M allocations: 1.450 GiB, 53.67% gc time)


┌ Info: Working on Trophy.Su
└ @ Main In[12]:5


  1.812679 seconds (2.30 M allocations: 1.450 GiB, 55.99% gc time)


┌ Info: Working on Trophy.He
└ @ Main In[12]:5


  1.831710 seconds (2.30 M allocations: 1.450 GiB, 56.74% gc time)


┌ Info: Working on Trophy.CaSc
└ @ Main In[12]:5


  1.944692 seconds (2.30 M allocations: 1.450 GiB, 56.59% gc time)


┌ Info: Working on Trophy.Om
└ @ Main In[12]:5


  1.925756 seconds (2.30 M allocations: 1.450 GiB, 52.44% gc time)


┌ Info: Working on Trophy.Pa
└ @ Main In[12]:5


  1.825125 seconds (2.30 M allocations: 1.450 GiB, 55.63% gc time)


┌ Info: Working on Burrowing.depth.0cm
└ @ Main In[12]:5


  1.975629 seconds (2.30 M allocations: 1.450 GiB, 55.87% gc time)


┌ Info: Working on Burrowing.depth.0.5cm
└ @ Main In[12]:5


  1.847809 seconds (2.30 M allocations: 1.450 GiB, 56.02% gc time)


┌ Info: Working on Burrowing.depth.5.15cm
└ @ Main In[12]:5


  1.851872 seconds (2.30 M allocations: 1.450 GiB, 56.53% gc time)


┌ Info: Working on Burrowing.depth..15cm
└ @ Main In[12]:5


  1.809327 seconds (2.30 M allocations: 1.450 GiB, 56.19% gc time)


### Write netCDF

In [15]:
@info "Writing netCDF file $(outputfile)"
write_traits_nc(outputfile, gridlonBenthos, gridlatBenthos, 
                trait_all, trait_err, varlist);

┌ Info: Writing netCDF file ../output/traits/Benthos_Traits_ab.nc
└ @ Main In[15]:1


## Plots

In [16]:
for ii = 1:ntraits
    make_plot_trait(gridlonBenthos, gridlatBenthos, trait_all[ii,:,:], varlist[ii]; vmin=0)
    figname = joinpath(figdirTraits, replace(varlist[ii], "." => "_"))
    PyPlot.savefig(figname, dpi=300, bbox_inches="tight")
    PyPlot.close_figs()
end

## Repeat with the other file

In [17]:
datafile = "/home/ctroupin/tmp/Emodnet-Bio/Traits/Benthos_Traits_tx.csv"
outputfile = joinpath(outputdirTraits, replace(basename(datafile), ".csv" => ".nc"))
@info "Output file: $(outputfile)"

if isfile(datafile)
    data,header = readdlm(datafile,',',header = true);
else
    @warn "Data file doesn't exist"
end
varlist = header[5:end];
ntraits = length(varlist);
@info "Working on $(ntraits) traits"

indexlon = findfirst(header .== "x").I[2];
indexlat = findfirst(header .== "y").I[2];
obslon = Vector{Float64}(data[:,indexlon]);
obslat = Vector{Float64}(data[:,indexlat]);

# Correlation length
len = 2.;
# Observational error variance normalized by the background error variance
epsilon2 = 5.;

rdiag=1.0./DIVAnd.weight_RtimesOne((obslon, obslat),(0.03,0.03))
@show maximum(rdiag),mean(rdiag);
epsilon2 = epsilon2*rdiag;

# Allocate matrix with all the gridded fields
trait_tx_all = Array{Float64}(undef, ntraits, length(gridlonBenthos), length(gridlatBenthos));
trait_tx_err = Array{Float64}(undef, length(gridlonBenthos), length(gridlatBenthos));
for i in 1:ntraits
    @info "Working on $(varlist[i])" 
    indextrait = findfirst(header .== varlist[i]).I[2];
    trait = Vector{Float64}(data[:,indextrait]) 
    traits_interp = traits_analysis(obslon, obslat, trait);
    if i == 1
        @info "Computing error field"
        trait_tx_err = traits_error(obslon, obslat, trait);
    end
    trait_tx_all[i,:,:] = traits_interp;
end

┌ Info: Working on 62 traits
└ @ Main In[17]:11


(maximum(rdiag), mean(rdiag)) = (439.414300295079, 33.47717862234115)


┌ Info: Working on Body.length..1cm
└ @ Main In[17]:31


  2.210487 seconds (2.30 M allocations: 1.450 GiB, 62.93% gc time)


┌ Info: Computing error field
└ @ Main In[17]:36
┌ Info: Working on Body.length.1.3cm
└ @ Main In[17]:31


  2.002002 seconds (2.30 M allocations: 1.450 GiB, 57.79% gc time)


┌ Info: Working on Body.length.3.10cm
└ @ Main In[17]:31


  1.957688 seconds (2.30 M allocations: 1.450 GiB, 57.57% gc time)


┌ Info: Working on Body.length.10.20cm
└ @ Main In[17]:31


  1.931009 seconds (2.30 M allocations: 1.450 GiB, 58.39% gc time)


┌ Info: Working on Body.length.20.50cm
└ @ Main In[17]:31


  2.021770 seconds (2.30 M allocations: 1.450 GiB, 58.98% gc time)


┌ Info: Working on Body.length..50cm
└ @ Main In[17]:31


  2.055061 seconds (2.30 M allocations: 1.450 GiB, 57.49% gc time)


┌ Info: Working on Fragility.Fragile
└ @ Main In[17]:31


  1.929420 seconds (2.30 M allocations: 1.450 GiB, 58.57% gc time)


┌ Info: Working on Fragility.Intermediate
└ @ Main In[17]:31


  2.098369 seconds (2.30 M allocations: 1.450 GiB, 58.06% gc time)


┌ Info: Working on Fragility.Robust
└ @ Main In[17]:31


  2.134956 seconds (2.30 M allocations: 1.450 GiB, 57.32% gc time)


┌ Info: Working on Motility.Swimmer
└ @ Main In[17]:31


  2.182033 seconds (2.30 M allocations: 1.450 GiB, 57.63% gc time)


┌ Info: Working on Motility.Tubicolous
└ @ Main In[17]:31


  2.173025 seconds (2.30 M allocations: 1.450 GiB, 57.00% gc time)


┌ Info: Working on Motility.Crawler
└ @ Main In[17]:31


  2.108748 seconds (2.30 M allocations: 1.450 GiB, 57.16% gc time)


┌ Info: Working on Motility.Crawler.Swimmer
└ @ Main In[17]:31


  2.279555 seconds (2.30 M allocations: 1.450 GiB, 58.77% gc time)


┌ Info: Working on Motility.Tubicolous.Crawler.Swimmer
└ @ Main In[17]:31


  2.064429 seconds (2.30 M allocations: 1.450 GiB, 59.70% gc time)


┌ Info: Working on Motility.Sessile
└ @ Main In[17]:31


  1.974701 seconds (2.30 M allocations: 1.450 GiB, 57.84% gc time)


┌ Info: Working on Motility.Sessile.Crawler.Swimmer
└ @ Main In[17]:31


  1.957948 seconds (2.30 M allocations: 1.450 GiB, 58.13% gc time)


┌ Info: Working on Lifespan..1year
└ @ Main In[17]:31


  1.971841 seconds (2.30 M allocations: 1.450 GiB, 58.27% gc time)


┌ Info: Working on Lifespan.1.3years
└ @ Main In[17]:31


  2.115939 seconds (2.30 M allocations: 1.450 GiB, 60.17% gc time)


┌ Info: Working on Lifespan.10.20years
└ @ Main In[17]:31


  2.018964 seconds (2.30 M allocations: 1.450 GiB, 59.39% gc time)


┌ Info: Working on Lifespan.3.10years
└ @ Main In[17]:31


  2.058753 seconds (2.30 M allocations: 1.450 GiB, 57.42% gc time)


┌ Info: Working on Lifespan..20years
└ @ Main In[17]:31


  2.187824 seconds (2.30 M allocations: 1.450 GiB, 60.45% gc time)


┌ Info: Working on Maturity..1year
└ @ Main In[17]:31


  2.096863 seconds (2.30 M allocations: 1.450 GiB, 57.32% gc time)


┌ Info: Working on Maturity.1.3years
└ @ Main In[17]:31


  2.248671 seconds (2.30 M allocations: 1.450 GiB, 59.37% gc time)


┌ Info: Working on Maturity.3.5years
└ @ Main In[17]:31


  2.247479 seconds (2.30 M allocations: 1.450 GiB, 61.04% gc time)


┌ Info: Working on Maturity..5years
└ @ Main In[17]:31


  2.118650 seconds (2.30 M allocations: 1.450 GiB, 58.41% gc time)


┌ Info: Working on Reproductive.frequency.Seasonal
└ @ Main In[17]:31


  2.263245 seconds (2.30 M allocations: 1.450 GiB, 56.13% gc time)


┌ Info: Working on Reproductive.frequency.Continuous
└ @ Main In[17]:31


  2.138857 seconds (2.30 M allocations: 1.450 GiB, 58.48% gc time)


┌ Info: Working on Fecundity..100
└ @ Main In[17]:31


  2.120347 seconds (2.30 M allocations: 1.450 GiB, 59.27% gc time)


┌ Info: Working on Fecundity.100.1000
└ @ Main In[17]:31


  1.961183 seconds (2.30 M allocations: 1.450 GiB, 58.64% gc time)


┌ Info: Working on Fecundity.1000.10000
└ @ Main In[17]:31


  1.945140 seconds (2.30 M allocations: 1.450 GiB, 58.82% gc time)


┌ Info: Working on Fecundity.10000.100000
└ @ Main In[17]:31


  1.924751 seconds (2.30 M allocations: 1.450 GiB, 57.44% gc time)


┌ Info: Working on Fecundity.100000.1000000
└ @ Main In[17]:31


  2.020968 seconds (2.30 M allocations: 1.450 GiB, 56.68% gc time)


┌ Info: Working on Fecundity..1000000
└ @ Main In[17]:31


  2.032037 seconds (2.30 M allocations: 1.450 GiB, 58.21% gc time)


┌ Info: Working on Offspring.type.Egg
└ @ Main In[17]:31


  1.966919 seconds (2.30 M allocations: 1.450 GiB, 58.70% gc time)


┌ Info: Working on Offspring.type.Larva
└ @ Main In[17]:31


  1.973495 seconds (2.30 M allocations: 1.450 GiB, 57.90% gc time)


┌ Info: Working on Offspring.type.Juvenile
└ @ Main In[17]:31


  1.939515 seconds (2.30 M allocations: 1.450 GiB, 58.34% gc time)


┌ Info: Working on Offspring.size..100
└ @ Main In[17]:31


  1.958670 seconds (2.30 M allocations: 1.450 GiB, 57.98% gc time)


┌ Info: Working on Offspring.size.100.500
└ @ Main In[17]:31


  1.949847 seconds (2.30 M allocations: 1.450 GiB, 57.91% gc time)


┌ Info: Working on Offspring.size.500.1500
└ @ Main In[17]:31


  1.974434 seconds (2.30 M allocations: 1.450 GiB, 57.63% gc time)


┌ Info: Working on Offspring.size..1500
└ @ Main In[17]:31


  1.963950 seconds (2.30 M allocations: 1.450 GiB, 58.00% gc time)


┌ Info: Working on Offspring.protection.None
└ @ Main In[17]:31


  1.915180 seconds (2.30 M allocations: 1.450 GiB, 58.44% gc time)


┌ Info: Working on Offspring.protection.Gel
└ @ Main In[17]:31


  1.922619 seconds (2.30 M allocations: 1.450 GiB, 58.06% gc time)


┌ Info: Working on Offspring.protection.Capsule
└ @ Main In[17]:31


  1.935373 seconds (2.30 M allocations: 1.450 GiB, 57.84% gc time)


┌ Info: Working on Offspring.protection.Burrying
└ @ Main In[17]:31


  1.948445 seconds (2.30 M allocations: 1.450 GiB, 58.26% gc time)


┌ Info: Working on Offspring.protection.Brooding
└ @ Main In[17]:31


  1.940597 seconds (2.30 M allocations: 1.450 GiB, 58.27% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.Null
└ @ Main In[17]:31


  1.937900 seconds (2.30 M allocations: 1.450 GiB, 58.01% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.1.15days
└ @ Main In[17]:31


  1.919005 seconds (2.30 M allocations: 1.450 GiB, 58.02% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.15.30days
└ @ Main In[17]:31


  1.964352 seconds (2.30 M allocations: 1.450 GiB, 58.66% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.1.2months
└ @ Main In[17]:31


  1.929334 seconds (2.30 M allocations: 1.450 GiB, 58.56% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration.2.6months
└ @ Main In[17]:31


  1.913572 seconds (2.30 M allocations: 1.450 GiB, 58.19% gc time)


┌ Info: Working on Offspring.pelagic.stage.duration..6months
└ @ Main In[17]:31


  1.931437 seconds (2.30 M allocations: 1.450 GiB, 58.24% gc time)


┌ Info: Working on Trophy.De
└ @ Main In[17]:31


  1.946517 seconds (2.30 M allocations: 1.450 GiB, 58.78% gc time)


┌ Info: Working on Trophy.SuDe
└ @ Main In[17]:31


  1.944928 seconds (2.30 M allocations: 1.450 GiB, 58.46% gc time)


┌ Info: Working on Trophy.Su
└ @ Main In[17]:31


  1.920058 seconds (2.30 M allocations: 1.450 GiB, 57.78% gc time)


┌ Info: Working on Trophy.He
└ @ Main In[17]:31


  1.946050 seconds (2.30 M allocations: 1.450 GiB, 58.59% gc time)


┌ Info: Working on Trophy.CaSc
└ @ Main In[17]:31


  1.914152 seconds (2.30 M allocations: 1.450 GiB, 58.26% gc time)


┌ Info: Working on Trophy.Om
└ @ Main In[17]:31


  1.910650 seconds (2.30 M allocations: 1.450 GiB, 58.24% gc time)


┌ Info: Working on Trophy.Pa
└ @ Main In[17]:31


  1.940495 seconds (2.30 M allocations: 1.450 GiB, 57.96% gc time)


┌ Info: Working on Burrowing.depth.0cm
└ @ Main In[17]:31


  1.920805 seconds (2.30 M allocations: 1.450 GiB, 57.95% gc time)


┌ Info: Working on Burrowing.depth.0.5cm
└ @ Main In[17]:31


  1.900560 seconds (2.30 M allocations: 1.450 GiB, 58.29% gc time)


┌ Info: Working on Burrowing.depth.5.15cm
└ @ Main In[17]:31


  1.933883 seconds (2.30 M allocations: 1.450 GiB, 58.66% gc time)


┌ Info: Working on Burrowing.depth..15cm
└ @ Main In[17]:31


  1.952531 seconds (2.30 M allocations: 1.450 GiB, 57.38% gc time)


In [18]:
write_traits_nc(outputfile, gridlonBenthos, gridlatBenthos, 
                trait_tx_all, trait_tx_err, varlist);

## Fish traits

In [25]:
datafile = "/home/ctroupin/tmp/Emodnet-Bio/Traits/Fish_Traits.csv"
outputfile = joinpath(outputdirTraits, replace(basename(datafile), ".csv" => ".nc"))
@info "Output file: $(outputfile)"

┌ Info: Output file: ../output/traits/Fish_Traits.nc
└ @ Main In[25]:3


In [19]:
if isfile(datafile)
    data,header = readdlm(datafile,',',header = true);
else
    @warn "Data file doesn't exist"
end
varlist = header[5:end];
ntraits = length(varlist);
@info "Working on $(ntraits) traits"

indexlon = findfirst(header .== "x").I[2];
indexlat = findfirst(header .== "y").I[2];
obslon = Vector{Float64}(data[:,indexlon]);
obslat = Vector{Float64}(data[:,indexlat]);

# Grid stored in emodnet_bio_grid.jl
xi,yi = DIVAnd.ndgrid(gridlonFish, gridlatFish);

# Mask
topodir = "../data/"
topofile = joinpath(topodir, "gebco_30sec_8.nc");

if isfile(topofile)
    bx, by, b = DIVAnd.load_bath(topofile,true,gridlonFish, gridlatFish);
    xmask, ymask, mmask = DIVAnd.load_mask(topofile,true,gridlonFish, gridlatFish,[0]);
else
    @error "Bathymetry file doesn't exist"
end
mmask = mmask[:,:,1]
@info size(mmask)

# Metrics
pm = ones(size(xi)) / (xi[2,1]-xi[1,1]);
pn = ones(size(xi)) / (yi[1,2]-yi[1,1]);

# Correlation length
len = 2.;
# Observational error variance normalized by the background error variance
epsilon2 = 5.;

rdiag=1.0./DIVAnd.weight_RtimesOne((obslon, obslat),(0.03,0.03))
@show maximum(rdiag),mean(rdiag);
epsilon2 = epsilon2*rdiag;

# Allocate matrix with all the gridded fields
trait_fish_all = Array{Float64}(undef, ntraits, length(gridlonFish), length(gridlatFish));
trait_fish_err = Array{Float64}(undef, length(gridlonFish), length(gridlatFish));
for i in 1:ntraits
    @info "Working on $(varlist[i])" 
    indextrait = findfirst(header .== varlist[i]).I[2];
    trait = Vector{Float64}(data[:,indextrait]) 
    traits_interp = traits_analysis(obslon, obslat, trait);
    if i == 1
        @info "Computing error field"
        trait_fish_err = traits_error(obslon, obslat, trait);
    end
    trait_fish_all[i,:,:] = traits_interp;
end

┌ Info: Output file: ../output/fish/Fish_Traits.nc
└ @ Main In[19]:3
┌ Info: Working on 36 traits
└ @ Main In[19]:12
┌ Info: (391, 261)
└ @ Main In[19]:33


(maximum(rdiag), mean(rdiag)) = (34.37624664581306, 7.778784558619619)


┌ Info: Working on Size.10.20cm
└ @ Main In[19]:52


  1.002369 seconds (1.72 M allocations: 998.738 MiB, 46.69% gc time)


┌ Info: Computing error field
└ @ Main In[19]:57
┌ Info: Working on Size.20.50cm
└ @ Main In[19]:52


  1.011944 seconds (1.72 M allocations: 998.738 MiB, 45.54% gc time)


┌ Info: Working on Size.50.100cm
└ @ Main In[19]:52


  1.056733 seconds (1.72 M allocations: 998.738 MiB, 45.39% gc time)


┌ Info: Working on Size.100.200cm
└ @ Main In[19]:52


  1.097789 seconds (1.72 M allocations: 998.738 MiB, 46.12% gc time)


┌ Info: Working on Size..200cm
└ @ Main In[19]:52


  1.073869 seconds (1.72 M allocations: 998.738 MiB, 47.43% gc time)


┌ Info: Working on Lifespan..5years
└ @ Main In[19]:52


  1.029280 seconds (1.72 M allocations: 998.738 MiB, 45.74% gc time)


┌ Info: Working on Lifespan.5.10years
└ @ Main In[19]:52


  1.018855 seconds (1.72 M allocations: 998.738 MiB, 45.93% gc time)


┌ Info: Working on Lifespan.10.15years
└ @ Main In[19]:52


  1.125334 seconds (1.72 M allocations: 998.738 MiB, 41.39% gc time)


┌ Info: Working on Lifespan.15.20years
└ @ Main In[19]:52


  1.031946 seconds (1.72 M allocations: 998.738 MiB, 45.55% gc time)


┌ Info: Working on Lifespan..20years
└ @ Main In[19]:52


  1.151136 seconds (1.72 M allocations: 998.738 MiB, 43.18% gc time)


┌ Info: Working on Maturity..5years
└ @ Main In[19]:52


  1.071138 seconds (1.72 M allocations: 998.738 MiB, 47.37% gc time)


┌ Info: Working on Maturity.5.10years
└ @ Main In[19]:52


  1.133482 seconds (1.72 M allocations: 998.738 MiB, 47.48% gc time)


┌ Info: Working on Maturity.10.15years
└ @ Main In[19]:52


  1.047433 seconds (1.72 M allocations: 998.738 MiB, 45.44% gc time)


┌ Info: Working on Maturity.15.20years
└ @ Main In[19]:52


  1.072286 seconds (1.72 M allocations: 998.738 MiB, 47.49% gc time)


┌ Info: Working on Maturity..20years
└ @ Main In[19]:52


  1.035236 seconds (1.72 M allocations: 998.738 MiB, 46.29% gc time)


┌ Info: Working on Fecundity..100
└ @ Main In[19]:52


  1.017467 seconds (1.72 M allocations: 998.738 MiB, 45.95% gc time)


┌ Info: Working on Fecundity.100.1000
└ @ Main In[19]:52


  1.011237 seconds (1.72 M allocations: 998.738 MiB, 45.93% gc time)


┌ Info: Working on Fecundity.1000.10000
└ @ Main In[19]:52


  1.014024 seconds (1.72 M allocations: 998.738 MiB, 46.00% gc time)


┌ Info: Working on Fecundity.10000.100000
└ @ Main In[19]:52


  1.074207 seconds (1.72 M allocations: 998.738 MiB, 46.28% gc time)


┌ Info: Working on Fecundity.100000.1000000
└ @ Main In[19]:52


  1.070870 seconds (1.72 M allocations: 998.738 MiB, 46.66% gc time)


┌ Info: Working on Fecundity..1000000
└ @ Main In[19]:52


  1.089109 seconds (1.72 M allocations: 998.738 MiB, 43.22% gc time)


┌ Info: Working on Offspring.type.Pelagic.egg
└ @ Main In[19]:52


  1.030996 seconds (1.72 M allocations: 998.738 MiB, 45.65% gc time)


┌ Info: Working on Offspring.type.Demersal.egg
└ @ Main In[19]:52


  1.042251 seconds (1.72 M allocations: 998.738 MiB, 45.15% gc time)


┌ Info: Working on Offspring.type.Juvenile
└ @ Main In[19]:52


  1.010310 seconds (1.72 M allocations: 998.738 MiB, 45.69% gc time)


┌ Info: Working on Offspring.size..1mm
└ @ Main In[19]:52


  1.007125 seconds (1.72 M allocations: 998.738 MiB, 45.84% gc time)


┌ Info: Working on Offspring.size.1.2mm
└ @ Main In[19]:52


  1.073611 seconds (1.72 M allocations: 998.738 MiB, 47.17% gc time)


┌ Info: Working on Offspring.size.2.3mm
└ @ Main In[19]:52


  1.025216 seconds (1.72 M allocations: 998.738 MiB, 46.09% gc time)


┌ Info: Working on Offspring.size..3mm
└ @ Main In[19]:52


  1.080443 seconds (1.72 M allocations: 998.738 MiB, 43.16% gc time)


┌ Info: Working on Trophic.type.Zoobenth
└ @ Main In[19]:52


  1.011152 seconds (1.72 M allocations: 998.738 MiB, 46.10% gc time)


┌ Info: Working on Trophic.type.ZoobenthNectiv
└ @ Main In[19]:52


  1.007070 seconds (1.72 M allocations: 998.738 MiB, 45.89% gc time)


┌ Info: Working on Trophic.type.Zooplankt
└ @ Main In[19]:52


  1.007321 seconds (1.72 M allocations: 998.738 MiB, 45.93% gc time)


┌ Info: Working on Trophic.type.Nectiv
└ @ Main In[19]:52


  1.129664 seconds (1.72 M allocations: 998.738 MiB, 44.61% gc time)


┌ Info: Working on Trophic.type.Omniv
└ @ Main In[19]:52


  1.086279 seconds (1.72 M allocations: 998.738 MiB, 47.06% gc time)


┌ Info: Working on Foraging.mode.Demersal
└ @ Main In[19]:52


  1.018783 seconds (1.72 M allocations: 998.738 MiB, 46.13% gc time)


┌ Info: Working on Foraging.mode.Benthopelagic
└ @ Main In[19]:52


  1.011829 seconds (1.72 M allocations: 998.738 MiB, 46.09% gc time)


┌ Info: Working on Foraging.mode.Pelagic
└ @ Main In[19]:52


  1.011961 seconds (1.72 M allocations: 998.738 MiB, 45.93% gc time)


In [28]:
write_traits_nc(outputfile, gridlonFish, gridlatFish, 
                trait_fish_all, trait_fish_err, varlist);